"""create patients and vitals tables

Revision ID: 99516ed26ce2
Revises: db9a62622ef1
Create Date: 2026-06-09 12:04:22.729348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import framework.infrastructure.persistence.types
import patients.infrastructure.persistence.types


# revision identifiers, used by Alembic.
revision: str = "99516ed26ce2"
down_revision: Union[str, Sequence[str], None] = "db9a62622ef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column(
            "id",
            framework.infrastructure.persistence.types.IdentityType(),
            nullable=False,
        ),
        sa.Column(
            "email",
            framework.infrastructure.persistence.types.EmailType(),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "vitals",
        sa.Column(
            "id",
            framework.infrastructure.persistence.types.IdentityType(),
            nullable=False,
        ),
        sa.Column(
            "patient_id",
            framework.infrastructure.persistence.types.IdentityType(),
            nullable=False,
        ),
        sa.Column(
            "heart_rate",
            patients.infrastructure.persistence.types.HeartRateType(),
            nullable=False,
        ),
        sa.Column(
            "systolic_blood_pressure",
            patients.infrastructure.persistence.types.SystolicBloodPressureType(),
            nullable=False,
        ),
        sa.Column(
            "temperature",
            patients.infrastructure.persistence.types.TemperatureType(),
            nullable=False,
        ),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vitals")
    op.drop_table("patients")
    # ### end Alembic commands ###
