"""Add first_name and last_name to app_user table

Revision ID: db9a62622ef1
Revises: fff4b0e5ecbb
Create Date: 2026-06-08 06:24:44.273451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db9a62622ef1"
down_revision: Union[str, Sequence[str], None] = "fff4b0e5ecbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_user", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("app_user", sa.Column("last_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_user", "last_name")
    op.drop_column("app_user", "first_name")
    # ### end Alembic commands ###
