"""create app_user table

Revision ID: fff4b0e5ecbb
Revises:
Create Date: 2026-06-02 00:46:22.343873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import framework.infrastructure.persistence.types


# revision identifiers, used by Alembic.
revision: str = "fff4b0e5ecbb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column(
            "id",
            framework.infrastructure.persistence.types.IdentityType(),
            nullable=False,
        ),
        sa.Column(
            "email",
            framework.infrastructure.persistence.types.EmailType(),
            nullable=False,
        ),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_app_user_email", "app_user", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_app_user_email", table_name="app_user")
    op.drop_table("app_user")
    # ### end Alembic commands ###
